[navigation]
docking_distance = 1.8; Расстояние до цели (в метрах), за которое отключается NavMesh и включается прямая доводка
arrival_distance = 0.2; Финишное расстояние остановки у точки WorkPoint (в метрах)

[age_ranges]
; Возраст при создании нового персонажа
min_starting_age = 16
max_starting_age = 33

[base_stats]
; Базовые физиологические характеристики персонажей по умолчанию fro each char
max_health = 100.0
move_speed = 1.0
work_speed = 1.0
eat_speed = 1.0     ; Время съедания 1 порции еды в секундах
hunger_rate = 0.048 ; Абсолютный прирост голода в секунду (+0.048 ед/сек). До максимальных 100 ед. персонаж проголодается за 35 минут реального времени.

[initial_stats]
; Стартовые физические и ментальные характеристики человека (в баллах)
strength = 10
intelligence = 10
endurance = 10
energy = 10
