[talents]
; Innate Genetic Talents (Talents) — Permanent Speed Multiplier (+25%)
forager = 1.25 ; Врождённый собиратель (плоды, ягоды, грибы)
worker = 1.25 ; Врождённый трудяга (тяжёлый физический труд, расчистка, снос)
craftsman = 1.25 ; Врождённый ремесленник (постройка укрытий, крафт)
scientist = 1.25
pioneer = 1.25
leader = 1.25
artist = 1.25

[talents_skills]
; slills mapping
forager = forager, farmer, hunter, fisher, lumberjack
worker = worker, miner
craftsman = craftsman, inventor, builder, engineer
scientist = healer, teacher
pioneer = pioneer, explorer, trader
leader = leader, guardian
artist = artist

[initial_skills]
; Стартовые уровни приобретаемых ремесленных навыков (Skills) от 0 до 10
forager = 0
worker = 0
builder = 0
trader = 0
lumberjack = 0
farmer = 0

[skill_progression]
; Настройки прогрессии и накопления опыта
speed_bonus_per_level = 0.1 ; +10% к скорости работы за каждый уровень навыка
max_level = 10 ; Максимальный уровень навыка
xp_per_work_cycle = 10.0 ; Опыт за 1 выполненный цикл
xp_talent_multiplier = 2.0; XP multiplier for talent
xp_for_level_up = 100.0 ; Опыт для перехода на следующий уровень
