[navigation]
docking_distance = 0.8; Расстояние до цели (в метрах), за которое отключается NavMesh и включается прямая доводка
arrival_distance = 0.4; Финишное расстояние остановки у точки WorkPoint (в метрах)

[age_ranges]
; Возраст при создании нового персонажа
min_starting_age = 16
max_starting_age = 33

[base_stats]
; base stats for each char
max_health = 100.0
move_speed = 1.0	; default move speed
work_speed = 1.0 	; default work multiplier for worksite work
eat_speed = 1.0     ; Время съедания 1 порции еды в секундах
hunger_rate = 0.048 ; Абсолютный прирост голода в секунду (+0.048 ед/сек). До максимальных 100 ед. персонаж проголодается за 35 минут реального времени.
energy_work_rate = -0.05
energy_rest_rate = 0.05
energy_drain_rate = -0.01
health_drain_rate = -0.1 ; abs per sec 

energy_eat_ratio = 1 ; nutrition to energy mult

energy_drain_hunger_threshold = 1 	; reduce energy when hungry > 1
health_energy_threshold = 10		; reduce health when energy < 10
health_hunger_threshold = 90		; reduce health when hunger > 90

cargo_drop_delay = 30.0	; потеря груза (sec), если некуда сдать

; think после отпускания перса (сек, random min..max)
think_time_min = 2.0
think_time_max = 5.0

; wander радиус (м, random min..max) — и wait, и blank
wander_radius_min = 5.0
wander_radius_max = 15.0

[initial_stats]
; Стартовые физические и ментальные характеристики человека (в баллах)
strength = 50
intelligence = 50
energy = 75
